### ISSUE TITLE
Versionsnummer wird nicht richtig angezeigt 

### ISSUE THREAD

**Issue by pioneersteffen** [mschlenstedt/Loxberry#1247]
Hallo,

als erstes vielen Dank für die Mühen für die Bereitstellung der Loxberry Plattform.

Beim Update auf die Version 2.0.0.3 wird die Version nicht richtig geschrieben, siehe Bild im Anhang. 

Vielen Dank.

Viele Grüße 
Steffen 
![69E220D4-BA58-4324-8963-177B8CFDEE21](https://user-images.githubusercontent.com/33648311/123630316-accd9880-d815-11eb-8830-d73049ff0645.png)
![F496EC31-FCDC-486F-BD47-E4B4951D3F70](https://user-images.githubusercontent.com/33648311/123630325-af2ff280-d815-11eb-9db1-d17dfce013d6.png)

**Comment by christianTF** [comment]
Das ist "by design". Wenn du auf "Version zurücksetzen" klickst, wird die Version auf eine Version vor der fehlerhaften gesetzt - so wie es im Feld auch geschrieben steht.
Wenn bei erneuter Installation die Fehlermeldung nicht verschwindet, bitte das Install-Log ansehen und den dortigen Fehler beheben, oder im Forum das Log melden.

lg, Christian
