### ISSUE TITLE
log_maint.pl identifiziert / als Emergency Cleanup-Grund

### ISSUE THREAD

**Issue by blacksun80** [mschlenstedt/Loxberry#1310]
[20220119_173256_750_Log Maintenance.log](https://github.com/mschlenstedt/Loxberry/files/7898846/20220119_173256_750_Log.Maintenance.log)

**Comment by christianTF** [comment]
Das Cleanup kommt irgendwie dazu, dass es / prüft, unter 25% feststellt und alle Logs aufräumt.
Das root-Verzeichnis dürfte gar nicht geprüft werden, weil nur Ramdisk-Drives aufgeräumt werden sollten.

**Comment by mschlenstedt** [comment]
Wir hatten uns wohl aus irgendeinem Grund mal entschieden, auch /opt/loxberry/log/system mit aufzuräumen. Das liegt im Root-FS, deswegen wird auch das RootFS mit aufgeräumt.

https://github.com/mschlenstedt/Loxberry/blob/1d0a72049933987aad73a8b03b7995807a2a0e44/sbin/log_maint.pl#L109

Den Grund kann ich nicht mehr sagen. Wir könnten es rausnehmen? Meinungen?

**Comment by mschlenstedt** [comment]
Letztendlich finde ich die gesamte Umsetzung eh etwas ungeschickt. Warum scannen wir den ganzen Mountpoint, wenn ich explizit nur im Unterverezeichnis "/opt/loxberry/log/plugins" aufräumen will? 

Das ist ein bisserl gefährlich... log_maint.pl läuft als root!

Der Check, ob aufgeräumt werden muss, muss natürlich gegen den Mountpoint erfolgen. Aber das Aufräumen an sich darf nur im gewünschten Verzeichnis erfolgen - denke ich.

**Comment by mschlenstedt** [comment]
Nach Analyse:

- log_maint.pl räumt nur in unseren Log-Verzeichnissen auf, nicht auf dem gesamten RootFS.
- Die Logmessage bzgl. RootFS war verwirrend: Da wir ~/log/system mit prüfen, wurde der freie Space auf dem RootFS kontrolliert

Allerdings war die prozentuale Prüfung für das RootFS (auf Grund der Größe) nicht sinnvoll. Wir haben jetzt eine Doppelprüfung: Space kleiner x % und Space < x MB. Die Grenzen sind 25% und 5% bzw. 200MB und 50 MB.

Fixed in 9c4acbaa01a50726461736fa9eb2f10be55da184
