### ISSUE TITLE
Healthcheck: Cannot read current CPU temperature

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#966]
Due Meldung kommt sporadisch beim Healthcheck, obwohl der TempSensor auslesbar ist. Wiederholt man den Test, wird die CPU-Temp. auch angezeigt.

**Comment by Cobru** [comment]
vielen Dank für Ihre e-mail


wir befinden uns bis 07.07.2019 im Urlaub.


In dringenden Fällen steht Ihnen einer unser Mitarbeiter 
unter der Telefonnummer 0177/2504543 zur Verfügung.






Vielen Dank für Ihr Verständnis.


Mit freundlichen Grüßen


Uwe Breede


ELNET Uwe Breede
Am Spielplatz 14
D-12559 Berlin


Tel.: 030 6549 5013
Fax : 030 6549 5015


www.elnet-elektro.de
info@elnet-elektro.de
Due Meldung kommt sporadisch beim Healthcheck, obwohl der TempSensor auslesbar ist. Wiederholt man den Test, wird die CPU-Temp. auch angezeigt.

-- 
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/mschlenstedt/Loxberry/issues/966

**Comment by christianTF** [comment]
Mit dem 1.5.0er Image auf Pi4 bekomme ich reproduzierbar keine Temperatur mehr, auch nach einem Tag.

![image](https://user-images.githubusercontent.com/14220265/64488553-aa1d4000-d249-11e9-81c3-dd456aea5056.png)

**Comment by mschlenstedt** [comment]
Kannst Du /sys/class/thermal/thermal_zone0/temp manuell auslesen? Und exisitiert in general.json die Watchdog-Config?

Die Config liefern wir nicht mit aus, sondern die wird erst erzeugt, wenn man das Watchdog-Widget das erste mal aufruft. Den Sensor lesen wir im Healthcheck aber mit aus: my $sensor = $cfgjson->{Watchdog}->{Tempsensor};

**Comment by christianTF** [comment]
> Kannst Du /sys/class/thermal/thermal_zone0/temp manuell auslesen? 

Ja, 39920

> Und exisitiert in general.json die Watchdog-Config?

Nein, nur Remote und Ram2Log

> Die Config liefern wir nicht mit aus, sondern die wird erst erzeugt, wenn man das Watchdog-Widget das erste mal aufruft. Den Sensor lesen wir im Healthcheck aber mit aus: my $sensor = $cfgjson->{Watchdog}->{Tempsensor};

Das dürfte das Problem sein. Ich hab keinen Watchdog konfiguriert. Die Temp. könnten wir im Healthcheck direkt auslesen, wenn das nur das `cat` ist. Im Watchdog steht die Temperatur dort.

**Comment by mschlenstedt** [comment]
Ich wollte das flexibel lassen für andere Plattformen. 

Aber wir könnten ein Default im Healthcheck setzen, falls die Watchdog Config nicht existiert.
