### ISSUE TITLE
RPI4: Swap zu groß

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#967]
Beim RPI4 wird auf Grund 4 GB RAM ein zu großes SWAP-File angelegt (5-6 GB). Die Routine in loxberryinit muss angepasst werden oder die maximale Größe des SWAP-Files begrenzt werden.

**Comment by Cobru** [comment]
vielen Dank für Ihre e-mail


wir befinden uns bis 07.07.2019 im Urlaub.


In dringenden Fällen steht Ihnen einer unser Mitarbeiter 
unter der Telefonnummer 0177/2504543 zur Verfügung.






Vielen Dank für Ihr Verständnis.


Mit freundlichen Grüßen


Uwe Breede


ELNET Uwe Breede
Am Spielplatz 14
D-12559 Berlin


Tel.: 030 6549 5013
Fax : 030 6549 5015


www.elnet-elektro.de
info@elnet-elektro.de
Beim RPI4 wird auf Grund 4 GB RAM ein zu großes SWAP-File angelegt (5-6 GB). Die Routine in loxberryinit muss angepasst werden oder die maximale Größe des SWAP-Files begrenzt werden.



-- 

You are receiving this because you are subscribed to this thread.

Reply to this email directly or view it on GitHub:

https://github.com/mschlenstedt/Loxberry/issues/967

**Comment by mschlenstedt** [comment]
setswap.pl wird gar nicht mehr ausgeführt?

**Comment by mschlenstedt** [comment]
Fixed with 35744c2dccf6235428eaa02c9cdf58b8f55e1b94
