### ISSUE TITLE
Remote Support funktioniert nicht mehr in Buster

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/Loxberry#978]
Zertifikatsproblem?

Umstellung auf neuen Server steht sowieso an. Gleich mit umsetzen.

**Comment by christianTF** [comment]
Paste WhatsApp:
Ich bin jetzt mal alles durch, scheint alles zu funktionieren, nur die Verbindung beim Remote-Support funktioniert nicht mehr 
TLS error: Unsupported protocol. This typically indicates that client and server have no common TLS version enabled. This can be caused by mismatched tls-version-min and tls-version-max options on client and server. If your OpenVPN client is between v2.3.6 and v2.3.2 try adding tls-version-min 1.0 to the client configuration to use TLS 1.0+ instead of TLS 1.0 only
Thu Jul 11 23:05:44 2019 OpenSSL: error:1425F102:SSL routines:ssl_choose_client_version:unsupported protocol

**Comment by mschlenstedt** [comment]
Erledigt mit Serverumzug.
